services:
  app:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    restart: always
